# cd ~/git/vabamorf_github/apps/cmdline/project/unix
# docker-compose build [IMAGE]
# docker-compose up -d
# docker-compose down
# docker-compose push

services:
  api_estnltk_sentok:
    image: tilluteenused/api_estnltk_sentok:2024.09.09
    ports:
      - 6000:6000
    environment:
      - MAX_CONTENT_LENGTH=5000000      
    build:
      context: ../../../../docker/flask_estnltk_sentok/
      dockerfile: ./Dockerfile

  api_vm_vmetajson:
    image: tilluteenused/api_vm_vmetajson:2024.02.29
    ports:
      - 7007:7007
    environment:
      - MAX_CONTENT_LENGTH=5000000      
    build:
      context: ../../../../docker/flask_vmetajson/
      dockerfile: ./Dockerfile
    depends_on:
      - api_estnltk_sentok

  api_vm_vmetyjson:
    image: tilluteenused/api_vm_vmetyjson:2024.02.29
    ports:
      - 7009:7009
    environment:
      - MAX_CONTENT_LENGTH=5000000      
    build:
      context: ../../../../docker/flask_vmetyjson/
      dockerfile: ./Dockerfile
    depends_on:
      - api_vm_vmetajson
