CC=g++
FLAGS=-O2 -DNDEBUG -Wall -std=gnu++0x -fdata-sections -ffunction-sections -Wl,--gc-sections
FILES=../../stlspeller/*.cpp ../../../../lib/proof/*.cpp ../../../../lib/etana/*.cpp ../../../../lib/fsc/*.cpp
LIBS=-pthread

all:
	$(CC) $(FLAGS) -o stlspeller $(FILES) $(LIBS)
