CC=g++
FLAGS=-O2 -DNDEBUG -Wall -std=gnu++0x -fdata-sections -ffunction-sections -Wl,--gc-sections
FILES=../../etsyn/*.cpp ../../../../lib/proof/*.cpp ../../../../lib/etana/*.cpp ../../../lib/*.cpp ../../../../lib/fsc/*.cpp
LIBS=-pthread

all:
	$(CC) $(FLAGS) -o etsyn $(FILES) $(LIBS)
