OUT=dct-t3mesta

CC=g++
FLAGS1=-O2 -DNDEBUG
FILES=../../$(OUT)/*.cpp ../../../../lib/etana/*.cpp ../../../../lib/fsc/*.cpp ../../../../lib/etyhh/*.cpp ../../../../lib/cmdline-old-style/*.cpp
FLAGS2=-pthread -ldl

all:
	$(CC) $(FLAGS1) -o $(OUT) $(FILES) $(FLAGS2)
	strip $(OUT)

clean:
	-rm $(OUT)

