# cd ~/git/vabamorf_github/docker/flask_vmetajson
# docker-compose up -d
# docker-compose down

services:
  api_vm_speller:
    image: tilluteenused/api_vm_vmetajson:2024.01.24
    ports:
      - 7007:7007
    environment:
      - MAX_CONTENT_LENGTH=5000000      
    build:
      context: ./
      dockerfile: ./Dockerfile
