# cd ~/git/vabamorf_github/docker/flask_vmetajson
# docker-compose up -d
# docker-compose down

services:
  api_estnltk_sentok:
    image: tilluteenused/api_estnltk_sentok:2024.01.23
    ports:
      - 6000:6000
    environment:
      - MAX_CONTENT_LENGTH=5000000      
    build:
      context: ../flask_estnltk_sentok
      dockerfile: ./Dockerfile

  api_vm_vmetajson:
    image: tilluteenused/api_vm_vmetajson:2024.02.03
    ports:
      - 7007:7007
    environment:
      - MAX_CONTENT_LENGTH=5000000      
    build:
      context: ./
      dockerfile: ./Dockerfile

