FROM python:3.8-slim-bullseye

# Install tini and create an unprivileged user
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini /sbin/tini
RUN addgroup --gid 1001 "vabamorf" && adduser --disabled-password --gecos "Vabamorf User,,," --home /vabamorf --ingroup vabamorf --uid 1001 vabamorf && chmod +x /sbin/tini

# Copy in just the requirements file
COPY --chown=vabamorf:vabamorf requirements.txt /vabamorf/

# Everything from here down runs as the unprivileged user account
USER vabamorf:vabamorf
WORKDIR /vabamorf

# Create a Python virtual environment for the dependencies
RUN python -m venv venv 
RUN /vabamorf/venv/bin/python -m pip install --upgrade pip
RUN venv/bin/pip --no-cache-dir install -r requirements.txt 

COPY --chown=vabamorf:vabamorf docker-entrypoint.sh flask_vmetajson.py vmetajson et.dct /vabamorf/

#ENV WORKERS=1
#ENV TIMEOUT=30
#ENV WORKER_CLASS=sync
#ENV LOGURU_LEVEL=INFO


RUN chmod +x ./docker-entrypoint.sh ./vmetajson ./flask_vmetajson.py
#ENTRYPOINT ["./docker-entrypoint.sh"]
#ENTRYPOINT ["exec", "/vabamorf/venv/bin/python3", "/vabamorf/flask_vmetajson.py", "--port=6000"]
CMD ./venv/bin/python3 ./flask_vmetajson.py --port=6000